### ISSUE TITLE
Distributed sorting on 4 nodes, unbalanced performance

### ISSUE THREAD

**Issue by MaChengxin** [MaChengxin/playground#2]
[Key moments of the distributed sorting application.pdf](https://github.com/MaChengxin/playground/files/4075893/Key.moments.of.the.distributed.sorting.application.pdf)
As can be seen in the figure above, the performance of distributed sorting on nodes tcn337-340 is not well balanced.
The finishing time of the computation part (i.e. sorting) is more or less acceptable, but the communication part took a varying time on each node.
This is because of the currently implementation of communication sends out the partitioned data in a sequential manner, in the order of: tcn337, tcn338, tcn339, tcn340.
tcn340 is unlucky since it's the last node every node (including itself) sends data to. If one node is blocked at sending data to tcn337, tcn338, or tcn339, tcn340 has nothing to do but simply to wait.

How can a sending be blocked? The current assumption is that sending uses Flight's `DoPut` method, which is a RPC. If the server's `DoPut` doesn't finish, the client's `DoPut` won't finish, either.
In this log: [tcn340.bullx_s.log](https://github.com/MaChengxin/playground/files/4076095/tcn340.bullx_s.log), sending to all nodes takes a lot of time, as compared with [tcn337.bullx_s.log](https://github.com/MaChengxin/playground/files/4076101/tcn337.bullx_s.log), [tcn338.bullx_s.log](https://github.com/MaChengxin/playground/files/4076103/tcn338.bullx_s.log), and [tcn339.bullx_s.log](https://github.com/MaChengxin/playground/files/4076105/tcn339.bullx_s.log), which took only a few seconds.
This is probably due to the fact that when tcn340 sends data to other nodes (and itself), the `ProcessReceivedData` function will be triggered:
https://github.com/MaChengxin/playground/blob/213ffbd543b0be85cadfe3174e2c9392732981ec/arrow/flight/my_flight/receive_and_merge.cc#L43

This can be confirmed by the log files: 
[tcn337.bullx_r.log](https://github.com/MaChengxin/playground/files/4076128/tcn337.bullx_r.log)
[tcn338.bullx_r.log](https://github.com/MaChengxin/playground/files/4076129/tcn338.bullx_r.log)
[tcn339.bullx_r.log](https://github.com/MaChengxin/playground/files/4076130/tcn339.bullx_r.log)
[tcn340.bullx_r.log](https://github.com/MaChengxin/playground/files/4076131/tcn340.bullx_r.log)

It also shows that receiving the data took only 2 - 3 seconds, but processing the data is longer.

To fix the issue, we need to:

- make sending partitioned data to other nodes parallelized, and
- instead of calling `ProcessReceivedData` from within `DoPut` when counter reaches 4, use another mechanism to trigger it.

**Comment by MaChengxin** [comment]
> How can a sending be blocked? The current assumption is that sending uses Flight's DoPut method, which is a RPC. If the server's DoPut doesn't finish, the client's DoPut won't finish, either.

This is not true.
The real cause is here:
https://github.com/MaChengxin/playground/blob/213ffbd543b0be85cadfe3174e2c9392732981ec/arrow/flight/my_flight/sender.cc#L20

The more accurate description is that the client's `writer->Close()` will be blocked if the server's `DoPut` hasn't finished.

See this log (of another "last node", temporary, log and corresponding change in source code unsaved):

> [Fri Jan 17 11:13:13 2020]: Before client->DoPut
> [Fri Jan 17 11:13:13 2020]: After client->DoPut
> [Fri Jan 17 11:13:13 2020]: Before writer->WriteRecordBatch
> [Fri Jan 17 11:13:13 2020]: After writer->WriteRecordBatch
> **[Fri Jan 17 11:13:13 2020]: Before writer->Close()
> [Fri Jan 17 11:13:42 2020]: After writer->Close()**
> [Fri Jan 17 11:13:44 2020]: Before client->DoPut
> [Fri Jan 17 11:13:44 2020]: After client->DoPut
> [Fri Jan 17 11:13:44 2020]: Before writer->WriteRecordBatch
> [Fri Jan 17 11:13:44 2020]: After writer->WriteRecordBatch
> **[Fri Jan 17 11:13:44 2020]: Before writer->Close()
> [Fri Jan 17 11:14:10 2020]: After writer->Close()**
> [Fri Jan 17 11:14:12 2020]: Before client->DoPut
> [Fri Jan 17 11:14:12 2020]: After client->DoPut
> [Fri Jan 17 11:14:12 2020]: Before writer->WriteRecordBatch
> [Fri Jan 17 11:14:12 2020]: After writer->WriteRecordBatch
> **[Fri Jan 17 11:14:12 2020]: Before writer->Close()
> [Fri Jan 17 11:14:36 2020]: After writer->Close()**
> [Fri Jan 17 11:14:38 2020]: Before client->DoPut
> [Fri Jan 17 11:14:38 2020]: After client->DoPut
> [Fri Jan 17 11:14:38 2020]: Before writer->WriteRecordBatch
> [Fri Jan 17 11:14:38 2020]: After writer->WriteRecordBatch
> **[Fri Jan 17 11:14:38 2020]: Before writer->Close()
> [Fri Jan 17 11:15:02 2020]: After writer->Close()**

The start time and finish time of `writer->Close()` on the client side is the same as the start time and finish time of `ProcessReceivedData` on the server side. This happens when we put `ProcessReceivedData` in `DoPut`.
[tcn91.bullx_r.log](https://github.com/MaChengxin/playground/files/4076414/tcn91.bullx_r.log)
[tcn95.bullx_r.log](https://github.com/MaChengxin/playground/files/4076415/tcn95.bullx_r.log)
[tcn98.bullx_r.log](https://github.com/MaChengxin/playground/files/4076416/tcn98.bullx_r.log)
[tcn103.bullx_r.log](https://github.com/MaChengxin/playground/files/4076417/tcn103.bullx_r.log)

**Comment by MaChengxin** [comment]
![Before fixing Issue #2_ run on tcn609, tcn954, tcn1164 and tcn1277](https://user-images.githubusercontent.com/7589678/72742355-d3f85300-3ba9-11ea-8bb6-d55d89a588d9.png)
This is measured after https://github.com/MaChengxin/playground/commit/5185fbaaa58fcaabc760f09ae3a585c7b01f2610 and before https://github.com/MaChengxin/playground/commit/409065d8450d5f1bbb3c50aef2dec47a7de3d783

**Comment by MaChengxin** [comment]
![After fixing Issue #2, run on tcn622, tcn627, tcn943 and tcn944](https://user-images.githubusercontent.com/7589678/72742484-1ae64880-3baa-11ea-9a27-0d81a35fbf5b.png)
This is the effect of https://github.com/MaChengxin/playground/commit/409065d8450d5f1bbb3c50aef2dec47a7de3d783

**Comment by tahashmi** [comment]
Execution time load balancing seems great after improvement.

**Comment by MaChengxin** [comment]
> instead of calling ProcessReceivedData from within DoPut when counter reaches 4, use another mechanism to trigger it

This is not done yet, but it is not a blocking issue now.
